from pygame.locals import *


# ゲーム全体系
SCR_RECT = Rect(0, 0, 640, 480)
FPS = 30
X = 0
Y = 1

# マップ系
STAGE_LENGTH = 2 ** 9
PIXCEL_OF_ONE_SIDE = 16
ROOP_SAND_MAKING = 5
ROOP_GLASS_MAKING = 3
ROOP_FOREST_MAKING = 3
ROOP_MOUNTAIN_MAKING = 5
WIDTH_SURROUND_GLASS = 30
WIDTH_SURROUND_FOREST = 150
WIDTH_SURROUND_MOUNTAIN = 220
N_RIVER = 12
SEA = 0
SAND = 1
GLASS = 2
FOREST = 3
MOUNTAIN = 4
RIVER = 5
PATH_DATA_DIR = '../data'
PATH_STAGE = '../data/map.pkl'
PATH_NATIONS = '../data/nations.pkl'
PATH_PLAYER = '../data/player.pkl'
PATH_SEA = '../img/sea1.png'
PATH_SAND = '../img/sand1.png'
PATH_GLASS = '../img/glass1.png'
PATH_FOREST = '../img/forest1.png'
PATH_MOUNTAIN = '../img/mountain1.png'
PATH_RIVER = '../img/river1.png'
WIDTH_IN_CELL = round(SCR_RECT.width / PIXCEL_OF_ONE_SIDE)
HEIGHT_IN_CELL = round(SCR_RECT.height / PIXCEL_OF_ONE_SIDE)
SCROLL_SPEED = 1
LIMIT_RIGHT_IN_PIXEL = (STAGE_LENGTH * PIXCEL_OF_ONE_SIDE) - (SCR_RECT.width / 2)
LIMIT_LEFT_IN_CELL = int(SCR_RECT.width / 2 / PIXCEL_OF_ONE_SIDE)
LIMIT_TOP_IN_CELL = int(SCR_RECT.height / 2 / PIXCEL_OF_ONE_SIDE)
LIMIT_RIGHT_IN_CELLS = int(STAGE_LENGTH - ((SCR_RECT.width / 2) / PIXCEL_OF_ONE_SIDE))
LIMIT_BOTTOM_IN_CELLS = int(STAGE_LENGTH - ((SCR_RECT.height / 2) / PIXCEL_OF_ONE_SIDE))

# プレーヤー系
PATH_IMAGE_PLAYER_UP = '../img/player_up.png'
PATH_IMAGE_PLAYER_RIGHT = '../img/player_right.png'
PATH_IMAGE_PLAYER_DOWN = '../img/player_down.png'
PATH_IMAGE_PLAYER_LEFT = '../img/player_left.png'
X_PLAYER = SCR_RECT.width / 2
Y_PLAYER = SCR_RECT.height / 2
DIRECTION_UP = 0
DIRECTION_RIGHT = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT   = 3

# 国家系
N_NATION = 10
N_NATION_NAME = 5
MAX_INIT_POPULATION = 10
MAX_POPULATION = 65535
NATION_LEVEL_VILLAGE = 0
NATION_LEVEL_TOWN = 1
NATION_LEVEL_CASTLE_TOWN = 2
NATION_LEVEL_CASTLE = 3
PATH_IMAGE_VILLAGE = '../img/village.png'
PATH_IMAGE_TOWN = '../img/town.png'
PATH_IMAGE_CASTLE_TOWN = '../img/castle_town.png'
PATH_IMAGE_CASTLE = '../img/castle.png'

# パラメータ系
MAX_INIT_PARAMETER = 5
NORMAL_BODY_TEMPERTURE = 36.5
MAX_PARAMETER = 100