from pygame.locals import *


# ゲーム全体系
SCR_RECT = Rect(0, 0, 640, 480)
FPS = 30
X = 0
Y = 1
MINUTE = 0
HOUR = 1
DAY = 2
MONTH = 3
YEAR = 4
JAN = 1
FEB = 2
MAR = 3
APR = 4
MAY = 5
JUN = 6
JUL = 7
AUG = 8
SEP = 9
OCT = 10
NOV = 11
DEC = 12
FONT_GOTHIC = '../font/font_1_honokamarugo_1.1.ttf'
FONT_MINCHO = '../font/font_1_honokamin.ttf'
COLOR_MAX = 255
COLOR_WHITE = (0, 0, 0)
COLOR_ORANGE = (255, 153, 0)
COLOR_JET_BLACK = (13, 0, 21)
COLOR_TIME = COLOR_WHITE
STRING_SIZE_TIME = 15
START_POINT_STRING_TIME = (SCR_RECT.width-170, 10)

# マップ系
STAGE_LENGTH = 2 ** 9
PIXCEL_OF_ONE_SIDE = 16
ROOP_SAND_MAKING = 5
ROOP_GLASS_MAKING = 3
ROOP_FOREST_MAKING = 3
ROOP_MOUNTAIN_MAKING = 5
WIDTH_SURROUND_GLASS = 30
WIDTH_SURROUND_FOREST = 150
WIDTH_SURROUND_MOUNTAIN = 220
N_RIVER = 12
SEA = 0
SAND = 1
GLASS = 2
FOREST = 3
MOUNTAIN = 4
RIVER = 5
PATH_DATA_DIR = '../data'
PATH_STAGE = '../data/map.pkl'
PATH_NATIONS = '../data/nations.pkl'
PATH_PLAYER = '../data/player.pkl'
PATH_TIMER = '../data/tiemer.pkl'
PATH_SEA = '../img/sea1.png'
PATH_SAND = '../img/sand1.png'
PATH_GLASS = '../img/glass1.png'
PATH_FOREST = '../img/forest1.png'
PATH_MOUNTAIN = '../img/mountain1.png'
PATH_RIVER = '../img/river1.png'
WIDTH_IN_CELL = round(SCR_RECT.width / PIXCEL_OF_ONE_SIDE)
HEIGHT_IN_CELL = round(SCR_RECT.height / PIXCEL_OF_ONE_SIDE)
SCROLL_SPEED = 1
LIMIT_RIGHT_IN_PIXEL = (STAGE_LENGTH * PIXCEL_OF_ONE_SIDE) - (SCR_RECT.width / 2)
LIMIT_LEFT_IN_CELL = int(SCR_RECT.width / 2 / PIXCEL_OF_ONE_SIDE)
LIMIT_TOP_IN_CELL = int(SCR_RECT.height / 2 / PIXCEL_OF_ONE_SIDE)
LIMIT_RIGHT_IN_CELLS = int(STAGE_LENGTH - ((SCR_RECT.width / 2) / PIXCEL_OF_ONE_SIDE))
LIMIT_BOTTOM_IN_CELLS = int(STAGE_LENGTH - ((SCR_RECT.height / 2) / PIXCEL_OF_ONE_SIDE))

# プレーヤー系
PATH_IMAGE_PLAYER_UP = '../img/player_up.png'
PATH_IMAGE_PLAYER_RIGHT = '../img/player_right.png'
PATH_IMAGE_PLAYER_DOWN = '../img/player_down.png'
PATH_IMAGE_PLAYER_LEFT = '../img/player_left.png'
X_PLAYER = SCR_RECT.width / 2
Y_PLAYER = SCR_RECT.height / 2
DIRECTION_UP = 0
DIRECTION_RIGHT = 1
DIRECTION_DOWN = 2
DIRECTION_LEFT   = 3

# 国家系
N_NATION = 10
N_NATION_NAME = 5
MAX_INIT_POPULATION = 10
MAX_POPULATION = 65535
NATION_LEVEL_VILLAGE = 0
NATION_LEVEL_TOWN = 1
NATION_LEVEL_CASTLE_TOWN = 2
NATION_LEVEL_CASTLE = 3
PATH_IMAGE_VILLAGE = '../img/village.png'
PATH_IMAGE_TOWN = '../img/town.png'
PATH_IMAGE_CASTLE_TOWN = '../img/castle_town.png'
PATH_IMAGE_CASTLE = '../img/castle.png'
NATION_SAND = 0
NATION_GLASS = 1
NATION_TREE = 2
NATION_WATER = 3
NATION_NOT_ENTER = 4
NATION_HOUSE = 5
NATION_HOUSE_DOOR = 6

# パラメータ系
MAX_INIT_PARAMETER = 5
NORMAL_BODY_TEMPERTURE = 36.5
MAX_PARAMETER = 100
MIN_PARAMETER = 0
EFFECT_BASE = 1
CORRECTION_1 = 3
CORRECTION_2 = 2
CORRECTION_3 = 1
CORRECTION_TUPLE = (CORRECTION_1, CORRECTION_2, CORRECTION_3)